# FIN3210 Week 2 Assignment

### Ma Kexuan 120090651

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import statsmodels.api as sm
from lifelines import CoxPHFitter

### Read the data from the disk

In [2]:
rrd_tot = pd.read_excel('FIN3210 Week 2 Renrendai loans.xlsx', sheet_name='Data Borrower')
plat_tot = pd.read_excel('FIN3210  Week 2 p2p lending platforms.xlsx', sheet_name='Platform Data')

In [3]:
rrd_tot.head(2)

,loanId,STATUS,BIDS,DEFAULT,AMOUNT,INTEREST,MONTHS,CREDIT,HOUSE,CAR,...,IND,CITY,PURPOSE,MARRY,AGE,opentime,readytime,title,description,nickName
0,2,CLOSED,9,0,3000,5.0,6,7,1,1,...,IT,北京,其他借款,未婚,33,2010-10-12 17:17:01,2010-10-15 11:00:49,庆祝上线,"看着人人贷经过精心的筹备,和长时间的内测,终于正式和大家见面了.特地来发个标, 希望大家多多...",一夫
1,11,CLOSED,8,0,3000,18.0,3,3,0,0,...,教育/培训,北京,其他借款,未婚,37,2010-10-18 16:40:38,2010-10-21 17:07:41,增加信用，重新发布借款,第一次借款不幸失败，这次特意做了收入审核。希望之前支持的朋友继续支持我，新朋友也可以看看我做...,郭遐

In [4]:
plat_tot.head()

,fullname,OnlineTime_YMD,Bankrupt_WDZJ,Province,City,Collapse,Benign,Fraud,RegCapital,Background,Capitaldeposit,Obtaininvest,Joinasso,Autobid,Transright,Riskdeposit,Thirdguarantee
0,123便利贷,20140519,20170413.0,上海,上海,1,0.0,0.0,500.0,民营系,0,0.0,1.0,0,0,0.0,0.0
1,17聚财,20151231,20170201.0,上海,上海,1,0.0,0.0,500.0,民营系,0,0.0,0.0,0,0,0.0,0.0
2,360易贷,20150504,20161201.0,辽宁,沈阳,1,0.0,0.0,500.0,民营系,0,0.0,0.0,1,1,0.0,0.0
3,365储蓄家,20180310,20180615.0,浙江,杭州,1,0.0,0.0,500.0,民营系,0,0.0,0.0,0,0,0.0,0.0
4,51丰收宝,20180320,20180724.0,广东,深圳,1,0.0,1.0,5.0,民营系,0,0.0,0.0,0,0,0.0,0.0

### 1)	Present two tables for the summary statistics of the key variables in Renrendai loans.xlsx and p2p lending platforms.xlsx
Procedures: Data cleaning, preserve the relevant data.

In [5]:
rrd = rrd_tot[['BIDS','DEFAULT','AMOUNT','INTEREST','MONTHS','CREDIT',
               'HOUSE','CAR','HOUSE_L','CAR_L','EDUCATION','WORKTIME',
               'INCOME','AGE']]
rrd.describe().T

,count,mean,std,min,25%,50%,75%,max
BIDS,10000.0,24.150600,41.342608,1.0,9.0,15.0,24.0,592.0
DEFAULT,10000.0,0.151300,0.358359,0.0,0.0,0.0,0.0,1.0
AMOUNT,10000.0,24545.835000,38280.756524,3000.0,8000.0,14400.0,26000.0,500000.0
INTEREST,10000.0,12.621900,2.273689,5.0,11.0,12.0,13.0,24.4
MONTHS,10000.0,12.237300,8.091090,3.0,6.0,12.0,12.0,36.0
CREDIT,10000.0,2.146300,1.530990,1.0,1.0,2.0,3.0,7.0
HOUSE,10000.0,0.564500,0.495847,0.0,0.0,1.0,1.0,1.0
CAR,10000.0,0.391700,0.488155,0.0,0.0,0.0,1.0,1.0
HOUSE_L,10000.0,0.228400,0.419823,0.0,0.0,0.0,0.0,1.0
CAR_L,10000.0,0.082200,0.274683,0.0,0.0,0.0,0.0,1.0
EDUCATION,9996.0,2.165966,0.818108,1.0,2.0,2.0,3.0,4.0
WORKTIME,9994.0,2.838003,0.992755,1.0,2.0,3.0,4.0,4.0
INCOME,9998.0,4.309162,1.335842,1.0,3.0,4.0,5.0,7.0
AGE,10000.0,34.755500,6.682708,24.0,30.0,33.0,38.0,53.0

In [6]:
plat = plat_tot[['OnlineTime_YMD','Bankrupt_WDZJ','Collapse','Benign',
                 'Fraud','RegCapital','Capitaldeposit','Obtaininvest',
                 'Joinasso','Autobid','Transright','Riskdeposit','Thirdguarantee']]
plat_des = plat.drop(['OnlineTime_YMD','Bankrupt_WDZJ'], axis = 1)
plat_des.describe().T

,count,mean,std,min,25%,50%,75%,max
Collapse,1000.0,0.782000,0.413094,0.0,1.0,1.0,1.0,1.0
Benign,782.0,0.098465,0.298134,0.0,0.0,0.0,0.0,1.0
Fraud,782.0,0.246803,0.431427,0.0,0.0,0.0,0.0,1.0
RegCapital,1000.0,596.064330,2328.221711,2.0,100.0,300.0,500.0,50000.0
Capitaldeposit,1000.0,0.191000,0.393286,0.0,0.0,0.0,0.0,1.0
Obtaininvest,968.0,0.026860,0.161756,0.0,0.0,0.0,0.0,1.0
Joinasso,968.0,0.054752,0.227613,0.0,0.0,0.0,0.0,1.0
Autobid,1000.0,0.244000,0.429708,0.0,0.0,0.0,0.0,1.0
Transright,1000.0,0.177000,0.381860,0.0,0.0,0.0,0.0,1.0
Riskdeposit,968.0,0.021694,0.145758,0.0,0.0,0.0,0.0,1.0
Thirdguarantee,968.0,0.034091,0.181557,0.0,0.0,0.0,0.0,1.0

### 2)	Perform a logit regression and examine the relation between the default likelihood and borrower characteristics such as credit, house, car, education, work time, etc.

In [7]:
X = rrd[['CREDIT','HOUSE','CAR','HOUSE_L','CAR_L','EDUCATION','WORKTIME']]
y = rrd[['DEFAULT']]
X = sm.add_constant(X)
logit_model = sm.Logit(y, X, missing = 'drop').fit()
logit_model.summary()

Optimization terminated successfully.
         Current function value: 0.332959
         Iterations 9

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                DEFAULT   No. Observations:                 9990
Model:                          Logit   Df Residuals:                     9982
Method:                           MLE   Df Model:                            7
Date:                Wed, 27 Sep 2023   Pseudo R-squ.:                  0.2170
Time:                        20:14:16   Log-Likelihood:                -3326.3
converged:                       True   LL-Null:                       -4247.9
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.6845      0.145     11.653      0.000       1.401       1.968
CREDIT        -1.8794      0.082    -22.814      0.000      -2.041      -1.718
HOUSE          0.2196      0.071      3.098      0.002       0.081       0.359
CAR           -0.3001      0.076     -3.972      0.000      -0.448      -0.152
HOUSE_L       -0.3484      0.090     -3.870      0.000      -0.525      -0.172
CAR_L          0.1327      0.133      0.995      0.320      -0.129       0.394
EDUCATION     -0.4453      0.040    -11.192      0.000      -0.523      -0.367
WORKTIME       0.0677      0.032      2.121      0.034       0.005       0.130
==============================================================================
"""

### 3)	Perform an ols regression and examine the relation between the number of bids and borrower characteristics such as credit, house, car, education, work time, etc.

In [8]:
X = rrd[['CREDIT','HOUSE','CAR','HOUSE_L','CAR_L','EDUCATION','WORKTIME']]
y = rrd[['BIDS']]
X = sm.add_constant(X)
ols_model = sm.OLS(y, X, missing = 'drop').fit()
ols_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   BIDS   R-squared:                       0.068
Model:                            OLS   Adj. R-squared:                  0.067
Method:                 Least Squares   F-statistic:                     103.3
Date:                Wed, 27 Sep 2023   Prob (F-statistic):          1.59e-146
Time:                        20:14:16   Log-Likelihood:                -50983.
No. Observations:                9990   AIC:                         1.020e+05
Df Residuals:                    9982   BIC:                         1.020e+05
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         10.6647      1.601      6.661      0.000       7.526      13.803
CREDIT         2.4966      0.273      9.162      0.000       1.962       3.031
HOUSE          3.9698      0.961      4.132      0.000       2.087       5.853
CAR           13.6067      0.933     14.578      0.000      11.777      15.436
HOUSE_L       -7.9274      1.087     -7.294      0.000     -10.058      -5.797
CAR_L         -8.0083      1.572     -5.094      0.000     -11.090      -4.926
EDUCATION     -4.2563      0.500     -8.512      0.000      -5.237      -3.276
WORKTIME       4.3018      0.419     10.276      0.000       3.481       5.122
==============================================================================
Omnibus:                    11755.651   Durbin-Watson:                   1.664
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1268326.871
Skew:                           6.304   Prob(JB):                         0.00
Kurtosis:                      56.741   Cond. No.                         19.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### 4)	Perform the Cox model (Proportional hazards model) and examine the relation between the platform default (survival) likelihood and platform characteristics such as RegCapital, Joinasso, etc.

In [9]:
cox_dt = plat[['OnlineTime_YMD','Bankrupt_WDZJ','Collapse','Benign','Fraud','RegCapital','Joinasso','Autobid','Transright','Riskdeposit','Thirdguarantee']]
cox_dt.dropna(inplace=True)
cox_dt['OnlineTime_YMD'] = pd.to_datetime(cox_dt['OnlineTime_YMD'], format='%Y%m%d')
cox_dt['Bankrupt_WDZJ'] = pd.to_datetime(cox_dt['Bankrupt_WDZJ'], format='%Y%m%d')
cox_dt['deltatime'] = (cox_dt['Bankrupt_WDZJ'] - cox_dt['OnlineTime_YMD']).apply(pd.Timedelta).dt.days
cox_dt.drop(['OnlineTime_YMD','Bankrupt_WDZJ'], axis=1, inplace=True)
cph = CoxPHFitter()
cph.fit(cox_dt, duration_col = 'deltatime', event_col = 'Collapse')
cph.print_summary()

<lifelines.CoxPHFitter: fitted with 774 total observations, 0 right-censored observations>
             duration col = 'deltatime'
                event col = 'Collapse'
      baseline estimation = breslow
   number of observations = 774
number of events observed = 774
   partial log-likelihood = -4324.21
         time fit was run = 2023-09-27 12:14:17 UTC

---
                 coef  exp(coef)   se(coef)   coef lower 95%   coef upper 95%  exp(coef) lower 95%  exp(coef) upper 95%
covariate
Benign          -0.32       0.72       0.13            -0.57            -0.07                 0.56                 0.93
Fraud            0.38       1.46       0.09             0.21             0.55                 1.23                 1.73
RegCapital      -0.00       1.00       0.00            -0.00             0.00                 1.00                 1.00
Joinasso        -0.90       0.41       0.22            -1.33            -0.46                 0.26                 0.63
Autobid         -0.26       0.77       0.09            -0.44            -0.08                 0.65                 0.92
Transright      -0.43       0.65       0.11            -0.65            -0.22                 0.52                 0.80
Riskdeposit     -0.10       0.91       0.27            -0.62             0.42                 0.54                 1.53
Thirdguarantee  -0.18       0.83       0.23            -0.63             0.26                 0.53                 1.30

                 cmp to     z      p   -log2(p)
covariate
Benign             0.00 -2.53   0.01       6.47
Fraud              0.00  4.38 <0.005      16.39
RegCapital         0.00 -0.16   0.87       0.20
Joinasso           0.00 -4.03 <0.005      14.15
Autobid            0.00 -2.83 <0.005       7.73
Transright         0.00 -3.94 <0.005      13.56
Riskdeposit        0.00 -0.37   0.71       0.50
Thirdguarantee     0.00 -0.81   0.42       1.25
---
Concordance = 0.64
Partial AIC = 8664.43
log-likelihood ratio test = 108.69 on 8 df
-log2(p) of ll-ratio test = 63.62